# Generated by Django 6.1.1 on 2026-09-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('frozen', 'Frozen'), ('broken', 'Streak Broken')], default='pending', max_length=10)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('freezes_left', models.IntegerField(default=3)),
                ('last_freeze_reset', models.CharField(default='2026-09', max_length=7)),
            ],
        ),
    ]
