# Generated by Django 6.1.1 on 2026-09-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_freeze_reset',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
