# Generated by Django 6.1.1 on 2026-10-01 15:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_task_last_freeze_reset'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('done', 'Done'), ('frozen', 'Frozen'), ('missed', 'Missed')], max_length=10)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_log', to='blog.task')),
            ],
            options={
                'unique_together': {('task', 'date')},
            },
        ),
    ]
